baseURL = "https://scarrilho.com/"
languageCode = "en-us"
title = "Sergio Carrilho"
theme = ["github.com/adityatelange/hugo-PaperMod"]

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName = true
  
[params.assets]
  disableFingerprinting = true

[params.profileMode]
  enabled = true
  title = "Sergio Carrilho"
  subtitle = "Tech Lead @ Sony | Agile | AI | KMP\n\nWelcome to my personal website. I write about technology, leadership, and software engineering."
  imageUrl = "/img/avatar.png"
  imageTitle = "Sergio Carrilho"
  imageWidth = 200
  imageHeight = 200
  
  [[params.profileMode.buttons]]
    name = "Articles"
    url = "/posts"
  
  [[params.profileMode.buttons]]
    name = "YouTube"
    url = "https://youtube.com/@sergiocarrilho"

  [[params.profileMode.buttons]]
    name = "SpeakerDeck"
    url = "https://speakerdeck.com/sony"
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/scarrilho"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/scarrilho"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/sergiocarrilho"
  [[params.socialIcons]]
    name = "medium"
    url = "https://sergiocarrilho.medium.com/"
  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@sergiocarrilho"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 5

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 15

