baseURL = "https://scarrilho.com/"
languageCode = "en-us"
title = "Sergio Carrilho"
theme = ["github.com/adityatelange/hugo-PaperMod"]

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName = true
  
[params.assets]
  disableFingerprinting = true

[params.profileMode]
  enabled = true
  title = "Sergio Carrilho"
  subtitle = "Tech Lead @ Sony | Agile | AI | KMP\n\nWelcome to my personal website. I write about technology, leadership, and software engineering."
  imageUrl = "/img/avatar.png"
  imageTitle = "Sergio Carrilho"
  imageWidth = 120
  imageHeight = 120
  
  [[params.profileMode.buttons]]
    name = "Read My Blog"
    url = "/posts"
  
  [[params.profileMode.buttons]]
    name = "YouTube"
    url = "https://youtube.com/@sergiocarrilho"

  [[params.profileMode.buttons]]
    name = "SpeakerDeck"
    url = "https://speakerdeck.com/scarrilho"
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/scarrilho"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/scarrilho"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/scarrilho"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10
